<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario asociate',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => 'gracias.html',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'secretaria@aega.com.ar',
		'to' => 'secretaria@aega.com.ar'
	),
	'fields' => array(
		'custom_U26343' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Apellidos y nombres completos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Apellidos y nombres completos\' es obligatorio.'
			)
		),
		'custom_U26373' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Datos adicionales / comentarios',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U26365' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Fecha y lugar de nacimiento / nacionalidad',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Fecha y lugar de nacimiento / nacionalidad\' es obligatorio.'
			)
		),
		'custom_U26347' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'CUIL / CUIL / CDI',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'CUIL / CUIL / CDI\' es obligatorio.'
			)
		),
		'custom_U26331' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Dni o pasaporte',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Dni o pasaporte\' es obligatorio.'
			)
		),
		'custom_U26327' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Email\' es obligatorio.'
			)
		),
		'custom_U26369' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Profesion / estudios cursados / idiomas',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Profesion / estudios cursados / idiomas\' es obligatorio.'
			)
		),
		'custom_U26352' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Sus productos o servicios / importa / exporta',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Sus productos o servicios / importa / exporta\' es obligatorio.'
			)
		),
		'custom_U26335' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Principales mercados / vínculo comercial con Galicia',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Principales mercados / vínculo comercial con Galicia\' es obligatorio.'
			)
		),
		'custom_U26356' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Empresas con las que mantiene vinculos en Galicia',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Empresas con las que mantiene vinculos en Galicia\' es obligatorio.'
			)
		),
		'custom_U26323' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Su empresa/dirección, ciudad, pais, mail, web',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Su empresa/dirección, ciudad, pais, mail, web\' es obligatorio.'
			)
		),
		'custom_U29963' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Domiciilio / calle / número / ciudad / pais',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Domiciilio / calle / número / ciudad / pais\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
